### ISSUE TITLE
How to make the people counter work if i want to change the middle line to side or somewhere in frame?

### ISSUE THREAD

**Issue by Naveennavik** [poojavinod100/People-Counting-Crowd-Density-Detection#3]
it works perfectly on this video whereas if i want to take the middle line which is kept at center to any othr place what is the procedure and which line i have to change it.Thanks in advance please help me out in this!!

**Comment by poojavinod100** [comment]
I think you have to change line number 192 in people_counter.py, which is:

cv2.line(frame, (0, H // 2), (W, H // 2), (0, 255, 255), 2)

Please refer the syntax of this function below to change the position of the line: 

Syntax: cv2.line(image, start_point, end_point, color, thickness)

Parameters:
image: It is the image on which line is to be drawn.
start_point: It is the starting coordinates of line. The coordinates are represented as tuples of two values i.e. (X coordinate value, Y coordinate value).
end_point: It is the ending coordinates of line. The coordinates are represented as tuples of two values i.e. (X coordinate value, Y coordinate value).
color: It is the color of line to be drawn. For BGR, we pass a tuple. eg: (255, 0, 0) for blue color.
thickness: It is the thickness of the line in px.
